%初始化参数结构体使用的函数
%参数的意义会在signal_enhance函数中给出
function [arg] = init_arg()
arg = struct( 'Fs', 1e5, 'filt_order', 2, 't_dis', 1,  'fft_left', 0.8, 'fft_right', 40, 'fs', 100, ...
        'delta_t', 1, 'interest_length', 0.3, ...
        'dwt_order', 2, 'wave', 'db2', ...
        'slice', 2);
end

